## Exponential operation on every element of a matrix / vector
### $u = e^v$

#### For loop version

In [21]:
import numpy as np
import math

n = 10
v = np.random.rand(n,1)
u = np.zeros((n,1))
# print(u, v)

In [22]:
for i in range(n):
    u[i] = math.exp(v[i])
print(u)

[[ 1.64936942]
 [ 2.08133201]
 [ 2.07167417]
 [ 1.78633125]
 [ 1.94468996]
 [ 1.83717409]
 [ 2.12708215]
 [ 1.71978609]
 [ 1.91717257]
 [ 2.19629529]]


#### Vectorized version

In [23]:
u = np.exp(v)
print(u)

[[ 1.64936942]
 [ 2.08133201]
 [ 2.07167417]
 [ 1.78633125]
 [ 1.94468996]
 [ 1.83717409]
 [ 2.12708215]
 [ 1.71978609]
 [ 1.91717257]
 [ 2.19629529]]


### $u =Av$

In [24]:
R = 10
C = 5
A = np.random.rand(R, C)
v = np.random.rand(C,1)
u = np.zeros((R,1))

print(A)
print(v)



[[ 0.51768145  0.16776658  0.07067473  0.94241456  0.79017131]
 [ 0.86229345  0.13890313  0.24023754  0.76588775  0.29564771]
 [ 0.57442104  0.07666977  0.83394082  0.49909786  0.46771632]
 [ 0.55075975  0.74367919  0.0507913   0.58848272  0.28005587]
 [ 0.729319    0.63533183  0.56664678  0.33766481  0.91408567]
 [ 0.42325955  0.70270748  0.15471936  0.91691729  0.11372088]
 [ 0.3824851   0.04276533  0.88800919  0.75316896  0.78575855]
 [ 0.884563    0.11963336  0.22119189  0.47038946  0.85570651]
 [ 0.22830616  0.53657979  0.45295098  0.39317996  0.1976483 ]
 [ 0.43978175  0.00994624  0.22037768  0.88695174  0.3456398 ]]
[[ 0.92386946]
 [ 0.18755447]
 [ 0.97057993]
 [ 0.66112871]
 [ 0.10351985]]


In [15]:
u = np.dot(A, v)

print(u)

[[ 1.48079316]
 [ 1.41534149]
 [ 1.15312125]
 [ 1.1013024 ]
 [ 1.29371416]
 [ 0.96203597]
 [ 1.30071894]
 [ 0.94470187]
 [ 0.8874274 ]
 [ 0.89276389]]
