In [1]:
import numpy as np

a = np.random.randn(5)  # Creates 5 gaussian random numbers stored in array a

In [2]:
print(a)

[ 0.92680842 -0.16735138  0.57452296  2.26459105 -1.53208536]


In [3]:
print(a.shape) # A rank 1 array, neither a row vector nor a column vector

(5,)


In [4]:
print(a.T) # Nothing happens because a is not a vector

[ 0.92680842 -0.16735138  0.57452296  2.26459105 -1.53208536]


In [5]:
print(a.T.shape)

(5,)


In [6]:
print(np.dot(a, a.T)) # Same effect

8.69271511785


GOOD PRACTICE: don't use rank-1 arrays

In [7]:
a = np.random.randn(5, 1) # Creates 5 gaussian random numbers stored in a (5, 1) MATRIX, i.e, a COLUMN VECTOR
print(a)

[[ 0.7933734 ]
 [-1.67498197]
 [ 0.22205426]
 [ 2.44350705]
 [ 0.15513084]]


In [8]:
print(a.T)

[[ 0.7933734  -1.67498197  0.22205426  2.44350705  0.15513084]]


In [9]:
print(np.dot(a, a.T)) # Now we get the OUTER PRODUCT of a vector (in this case, equivalent to a matrix multiplication (5x1)(1x5))

[[ 0.62944135 -1.32888614  0.17617195  1.93861349  0.12307668]
 [-1.32888614  2.80556461 -0.37193689 -4.09283026 -0.25984136]
 [ 0.17617195 -0.37193689  0.0493081   0.54259116  0.03444746]
 [ 1.93861349 -4.09283026  0.54259116  5.97072671  0.3790633 ]
 [ 0.12307668 -0.25984136  0.03444746  0.3790633   0.02406558]]


To check and make sure:

In [10]:
assert(a.shape == (5,1))

Assertions are a systematic way to check that the internal state of a program is as the programmer expected, with the goal of catching bugs. In particular, they're good for catching false assumptions that were made while writing the code, or abuse of an interface by another programmer. In addition, they can act as in-line documentation to some extent, by making the programmer's assumptions obvious. ("Explicit is better than implicit.")

When your code assumes something and acts upon the assumption, it's recommended to protect this assumption with an assert. This assert failing means your assumption isn't correct, which means your code isn't correct.

*assert condition*
 
is equivalent to:

*if not condition:
    raise AssertionError()*

As a "last call" resource:

In [ ]:
a = np.random.randn(5)  # Creates 5 gaussian random numbers stored in array a
a = reshape((5,1))